image: node
 
stages: 
 - lint
 
eslint:
 stage: lint
 
 script:
   - npm i -g eslint
   - npm install eslint-config-airbnb
   - npx install-peerdeps eslint-config-airbnb
   - eslint --ext js,jsx .
 
